### PR TITLE
A much improved infinite grid widget.

### PR DESCRIPTION
**Pull request by pz-2015**
1. completely changed implementation of infinite grid widget for a much smoother scrolling experience;
2. added params option for infinite grid for allowing additional query
parameters;
3. modified sample in routers for easier test;

### CODE REVIEW

**Comment by pz-2015** [comment]
4. added nested "datakey" and "totalkey" extracting ability

**Comment by pz-2015** [comment]
5. corrected scroll cushion for fast scrolling.
6. added ability for customizing additional query parameter.

**Comment by bluekvirus** [comment]
@mr-beaver item 5 contains the spinner right?

**Comment by pz-2015** [comment]
spinning icon added;

7). added loading spinning icon when user scrolls too fast;
8). corrected bug when scorlling up the contents are not thoroughly cleaned

**Comment by pz-2015** [comment]
9). fixed bug when scrolling up, there is no spinning icon.
10). new solution coming in soon.

**Pull request closed without merging**
